source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/L.GF/CocopodsSpec.git'
use_frameworks!
platform :ios, '8.0'

target 'CodeDemos' do
pod 'Masonry'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'FMDB'
pod 'YLGIFImage', '~> 0.11'
pod 'QDDNet'
end

